name: Node.js CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: CI-CD-NodeApp

      - name: Run tests
        run: npm test
        working-directory: CI-CD-NodeApp

      - name: Login to DockerHub
        run: echo "${{ secrets.jagrutib27 }}" | docker login -u "${{ secrets.jagrutib27 }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.jagrutib27 }}/node-cicd-demo .
        working-directory: CI-CD-NodeApp

      - name: Push Docker image
        run: docker push ${{ secrets.jagrutib27 }}/node-cicd-demo
